Try to add a problem matcher

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,6 +22,13 @@ jobs:
       #     key: ${{ github.workflow }}-${{ env.WEEK }}-{hash}
       #     restore-keys: |
       #       ${{ github.workflow }}-${{ env.WEEK }}-
+      - name: Install Problem Matchers
+        run: |
+          echo "::add-matcher::.github/problem-matcher.json"
+          file="/dockerfiles/steps/step-prebake.bash"
+          line=26
+          echo "$file: line $line, col 1, Error - line not covered by tests. (coverage-error)"
+          exit 1
       - name: Setup Python
         uses: actions/setup-python@v2
         with:
